server:
  error:
    include-message: always
    include-binding-errors: always
  port: 8080

#### Postgres and JPA configurations
spring:
  datasource:
    password: password
    url: jdbc:postgresql://localhost:5433/registration
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show_sql: true
  ### MailDEV configurations ###
  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello
  ### MailDEV configurations ###
    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000